### PR TITLE
page orientation

### PR DESCRIPTION
**Pull request by maranath**
added the page orientation and the modified parameters: paper size "A4" = 9, and margins, headers and footers

### CODE REVIEW

**Comment by dbzhang800** [comment]
Hi, thanks for you contribution. 

Maybe we should introduce a new class QXlsx::PageSettings, then we can add read and write support for page settings easier.

**Comment by maranath** [comment]
Yes, probably it would be better, I'll try to do just that
07.01.2015 08:53, Debao Zhang пишет:
> Maybe we should introduce a new class QXlsx::PageSettings, then we can 
> add read and write support for page settings easier.

**Comment by bat-ventzi** [comment]
I've implemented some of the print functionality here https://github.com/dbzhang800/QtXlsxWriter/pull/93. I am also thinking that this functionality should be in its own class, but I don't have the time for this.

**Comment by VSRonin** [comment]
As the author is not active any more, please submit your pull request to https://github.com/VSRonin/QtXlsxWriter I'll take care of maintaining code until the author is back

**Comment by maranath** [comment]
Added the ability to change the PageBreakPreview parameter to switch 
View-> Page layout or normal

**Pull request closed without merging**
